/**
 * The drift guard for `templates.ts`.
 *
 * `samples/*.json` is regenerated by `mtg.test.ts` / `holdem.test.ts` on every `npm test`, and the
 * chooser declares each sample's card and seat counts rather than parsing 165 KB of JSON to show a
 * dialog. So the declared numbers get checked against the real file here: a regenerated sample that
 * gains a card fails this instead of shipping a blurb that lies. The `ok` assertion doubles as the
 * check that both bundled files are still importable at all.
 */

import { describe, expect, it } from 'vitest';
import { importJson } from '../stores/persistence';
import { TEMPLATES } from './templates';

describe.each(TEMPLATES)('the $name template', (template) => {
  it('is a valid definition whose blurb matches it', async () => {
    const result = importJson(await template.load());
    expect(result.ok ? [] : result.errors).toEqual([]);
    if (!result.ok) return;

    expect(result.definition.name).toBe(template.name);
    expect(result.definition.templates).toHaveLength(template.cards);
    expect(result.definition.playerCount).toBe(template.players);
  });
});
