/**
 * Step 47 — GATE, phase 4. §8's own words: "Re-author a trimmed `mtgish` and `vtesish` **through the
 * UI**, export, and diff against the TypeScript fixtures."
 *
 * This file renders the real authoring screens (via the real route table, the real store, the real
 * IndexedDB-backed layout — exactly `rules.test.tsx`/`cards.test.tsx`'s idiom) and drives them with
 * `userEvent`, the way a designer would: clicks, selects, typed text. Nothing here calls a store
 * action directly except the one-time seed of an empty game (the same seed every authoring test in
 * this repo already performs before it starts clicking).
 *
 * TRIMMED, deliberately (§8 step 47's own instruction): this does not rebuild either fixture card for
 * card. It covers every DISTINCT v2 construct the two fixtures actually use — determined by grepping
 * `mtgish.ts`/`vtesish.ts` for `kind:` literals, not by guessing — and no more. A construct proven
 * once (in either fixture) is not re-proven in the other; the report names which fixture proves which
 * construct. The v2-new inventory, and where each is proven:
 *
 *   RuleSet modes    continuous, modifier, replacement, activation   — both fixtures use all four
 *   Effect kinds     announceAction, counterAction, attach,           — mtgish
 *                    setController, eliminateSeat
 *                    sealedChoice                                     — vtesish
 *   TargetSelector   matching, hostOf                                 — mtgish (matching also vtesish)
 *   CardRef          host, candidate                                  — mtgish
 *   SeatRef          owner                                            — mtgish
 *                    relative, sum (quantifier)                       — vtesish
 *   ActionSelector   action{ref:topOfStack}                           — mtgish
 *   PriorityWindow   non-default fields (start, includeStart)         — vtesish
 *
 * `attachedTo` (TargetSelector), `controller` (SeatRef), `replacedTarget` (CardRef), and
 * `cardTag`/`activeSeatCount`/`replacedAmount`/`actionField` (ValueRef) are v2-new but used by
 * NEITHER fixture (confirmed by the same grep) — already proven authorable by
 * `selectorChips.test.tsx`/`refChips.test.tsx`/`effectRow.test.tsx`, not re-proven here.
 *
 * Diff strategy (§8's own instruction: construct by construct, not one opaque blob): ids are
 * autogenerated by the store (`p1`, `z1`, `rs1`, …) and cannot match the fixtures' hand-picked
 * constants, so a byte-for-byte `toEqual` against `mtgish`/`vtesish` is impossible by construction —
 * and would prove nothing about the UI even if it were. Instead, every semantic field (kind unions,
 * operators, literals, offsets, mode flags) is asserted against the fixture's own literal value, and
 * every id-shaped field is asserted to resolve to the right AUTHORED entity by construction (the
 * variable holding the id IS the entity), which is the strongest claim byte-identity could add.
 *
 * Comments below say "AC-adjacent: <id>" rather than "AC: <id>" deliberately: `traceability.test.ts`
 * scans every `.test.tsx?` file for the literal string "AC:" and treats it as a proof-file for that
 * criterion. This file corroborates several MTG/V criteria (the same outcome, on a re-authored and
 * round-tripped definition) but is not their traceability record — the engine/component tests §9.1
 * names already are, and duplicating the tag here would make the traceability table claim two
 * "kinds" of proof (headless behavioural vs. UI-authored-then-replayed) as one undifferentiated list.
 */

import 'fake-indexeddb/auto';
import { RouterProvider, createMemoryRouter } from 'react-router-dom';
import { act, fireEvent, render, screen, waitFor, within } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { beforeEach, describe, expect, it } from 'vitest';
import { CONTINUE, START_STATE_ID, type GameDefinition, type LogLine } from '../../engine/types';
import { step } from '../../engine/dispatch';
import { exportJson, importJson } from '../../engine/schema';
import { emptyBoard, place } from '../../test/board';
import { createEmptyDefinition, useDefinitionStore } from '../../stores/definitionStore';
import { deleteGame, getAllGames, putGame } from '../../stores/persistence';
import { routes } from '../../routes';
import * as mtg from '../../test/fixtures/mtgish';
import * as vtes from '../../test/fixtures/vtesish';

const GAME_ID = 'g1';
const definition = (): GameDefinition => useDefinitionStore.getState().definition;

/** Every authoring test in this repo seeds a blank, valid game and drives everything else through
 *  the UI from there — `playerCount` has no editor screen (it is set at game-creation time, outside
 *  this phase's scope), so it is the one field seeded rather than clicked. */
async function seed(playerCount: number): Promise<void> {
  for (const game of await getAllGames()) await deleteGame(game.id);
  useDefinitionStore.getState().setDefinition(createEmptyDefinition('blank', 'blank', '2026-01-01T00:00:00.000Z'));
  localStorage.clear();
  await putGame({
    ...createEmptyDefinition(GAME_ID, 'Reauthored', '2026-01-01T00:00:00.000Z'),
    playerCount,
  });
}

function openGame(path = `/game/${GAME_ID}/pools`) {
  const router = createMemoryRouter(routes, { initialEntries: [path] });
  const utils = render(<RouterProvider router={router} />);
  return { router, user: userEvent.setup(), ...utils };
}

type Router = ReturnType<typeof openGame>['router'];
type User = ReturnType<typeof openGame>['user'];

async function goto(router: Router, path: string) {
  await act(async () => {
    await router.navigate(path);
  });
}

/** Adds a rule, which navigates straight to its editor (RuleSetsScreen's own behaviour) — returns
 *  its id, then leaves the router parked on the new rule's route. Caller navigates back to add more. */
async function addRule(router: Router, user: User): Promise<string> {
  await goto(router, `/game/${GAME_ID}/rules`);
  await screen.findByRole('button', { name: 'Add rule' });
  await user.click(screen.getByRole('button', { name: 'Add rule' }));
  await waitFor(() => expect(router.state.location.pathname).toMatch(/\/rules\/.+$/));
  return definition().ruleSets.at(-1)!.id;
}

async function addTemplate(router: Router, user: User): Promise<string> {
  await goto(router, `/game/${GAME_ID}/cards`);
  await screen.findByRole('button', { name: 'Add card' });
  await user.click(screen.getByRole('button', { name: 'Add card' }));
  await waitFor(() => expect(router.state.location.pathname).toMatch(/\/cards\/.+$/));
  return definition().templates.at(-1)!.id;
}

/** Points a "Left side"/"Right side"/"Amount" ValueRefPicker chip at `cardIndex(<cardKind>, indexId)`. */
async function setCardIndexRef(
  user: User,
  chip: HTMLElement,
  cardRadioName: string | RegExp,
  indexId: string
) {
  await user.click(chip);
  await user.click(screen.getByRole('radio', { name: 'A card index' }));
  await user.click(screen.getByRole('button', { name: 'Card' }));
  await user.click(screen.getByRole('radio', { name: cardRadioName }));
  await user.selectOptions(screen.getByRole('combobox', { name: 'Index' }), indexId);
}

/**
 * Every condition-shaped field authored through the UI (`rule.condition`, `activation.costCheck`,
 * `matching.where`) comes out wrapped in a one-child AND group — `CriteriaGroupEditor`'s "+
 * condition" always operates on a `CriteriaGroup`, never produces a bare `GameCriteria` at the top.
 * mtgish.ts/vtesish.ts, hand-written TypeScript object literals with no such constraint, use a BARE
 * criteria directly for several of these fields (`lethalCondition`, the `oustRule` condition,
 * `equipmentAbilityRule.activation.costCheck`). This is snag (3) from the task brief, generalised:
 * every occurrence below is asserted against the group-wrapped shape the UI actually produces, which
 * is semantically identical (an AND of one child is that child) but not byte-identical to the
 * fixture's own literal — the difference is asserted deliberately, not normalised away.
 */
const oneCriteria = (node: object) => ({ kind: 'group' as const, combinator: 'and' as const, children: [node] });

/**
 * `ChipPopover` only closes on Escape or a pointerdown OUTSIDE its own wrapper (`ChipPopover.tsx`) —
 * it never closes itself just because its value was set. Two chips sharing a generic field label
 * ("Zone", "Card", "Index", "Of") both left open at once makes `getByRole` ambiguous, so every
 * distinct chip's configuration below that is followed by opening ANOTHER, non-nested chip closes
 * this one first. The "Kind" heading is present and inert on every rule editor screen, so it is a
 * safe universal click-outside target.
 */
async function closePopovers(user: User) {
  await user.click(screen.getByRole('heading', { name: 'Kind' }));
}

const effectsList = () => within(screen.getByRole('list', { name: 'Effects' }));
const effectRow = (n: number) => within(effectsList().getAllByRole('listitem')[n - 1]);
const ifBand = () => within(screen.getByRole('region', { name: 'If' }));

beforeEach(async () => {
  for (const game of await getAllGames()) await deleteGame(game.id);
});

// ============================================================================================
// mtgish
// ============================================================================================

describe('mtgish, re-authored through the UI', () => {
  it('exports, imports, and plays like the corresponding constructs in mtgish.ts', async () => {
    await seed(2);
    const { router, user } = openGame();

    // -- Pools ---------------------------------------------------------------------------------
    await screen.findByRole('button', { name: 'Add pool' });
    await user.click(screen.getByRole('button', { name: 'Add pool' }));
    const lifeId = definition().pools[0].id;
    await user.type(screen.getByRole('spinbutton', { name: 'Starting value' }), '20');
    await user.type(screen.getByRole('spinbutton', { name: 'Minimum' }), '0');
    await user.type(screen.getByRole('spinbutton', { name: 'Maximum' }), '20');

    // -- Zones — §9.3's four. Library/Graveyard/Hand match the add-time defaults except where noted.
    await goto(router, `/game/${GAME_ID}/zones`);
    await user.click(await screen.findByRole('button', { name: 'Add zone' })); // Library
    const libraryId = definition().zones[0].id;
    await user.selectOptions(screen.getByRole('combobox', { name: 'Visibility' }), 'faceDown');

    await user.click(screen.getByRole('button', { name: 'Add zone' })); // Hand — the newly-added
    // zone is the one selected in the master/detail pane, so its fields are the only ones on screen.
    const handId = definition().zones[1].id;
    await user.selectOptions(screen.getByRole('combobox', { name: 'Visibility' }), 'ownerOnly');
    await user.selectOptions(screen.getByRole('combobox', { name: 'Layout' }), 'fan');

    await user.click(screen.getByRole('button', { name: 'Add zone' })); // Battlefield — shared, row, unordered
    const battlefieldId = definition().zones[2].id;
    await user.selectOptions(screen.getByRole('combobox', { name: 'Scope' }), 'shared');
    await user.selectOptions(screen.getByRole('combobox', { name: 'Layout' }), 'row');
    await user.click(screen.getByRole('checkbox', { name: 'Ordered' }));

    await user.click(screen.getByRole('button', { name: 'Add zone' })); // Graveyard — every default matches
    const graveyardId = definition().zones[3].id;
    // Not referenced by any rule in this trim (mtgish's Graveyard only ever receives a `moveCard`
    // action in the fixture's own scripted play, not through an authored rule) — asserted to exist
    // rather than silently dropped, per the "assert explicitly rather than deleting" instruction.
    expect(definition().zones.find((z) => z.id === graveyardId)).toMatchObject({ visibility: 'faceUp' });

    // -- Priority window — WINDOW_STACK: active/forward/includeStart:true/passesToClose:null are
    // every field's add-time default, so adding it is the whole job (§4.6).
    await goto(router, `/game/${GAME_ID}/priority`);
    await user.click(await screen.findByRole('button', { name: 'Add window' }));
    const windowStackId = definition().priorityWindows[0].id;

    // -- Card indexes live on templates — create Bear now so POWER/TOUGHNESS/DAMAGE exist before any
    // rule needs to reference them.
    const bearId = await addTemplate(router, user);
    await user.type(screen.getByRole('textbox', { name: 'Tags' }), 'creature');
    await user.click(screen.getByRole('button', { name: /add a number/i }));
    let names = screen.getAllByRole('textbox', { name: 'Name' });
    await user.clear(names[0]);
    await user.type(names[0], 'Power');
    let starts = screen.getAllByRole('spinbutton', { name: 'Starting value' });
    await user.type(starts[0], '2');

    await user.click(screen.getByRole('button', { name: /add a number/i }));
    names = screen.getAllByRole('textbox', { name: 'Name' });
    await user.clear(names[1]);
    await user.type(names[1], 'Toughness');
    starts = screen.getAllByRole('spinbutton', { name: 'Starting value' });
    await user.type(starts[1], '2');

    await user.click(screen.getByRole('button', { name: /add a number/i }));
    names = screen.getAllByRole('textbox', { name: 'Name' });
    await user.clear(names[2]);
    await user.type(names[2], 'Damage');

    const [powerId, toughnessId, damageId] = definition().templates.find((t) => t.id === bearId)!.indexes.map(
      (i) => i.id
    );

    const boltId = await addTemplate(router, user);
    const counterMagicId = await addTemplate(router, user);
    // Anthem Lord carries the modifier rule. It gets its own template rather than riding on Bear
    // (mtgish.ts does the same — `anthemLordRule` is on RS_ANTHEM_LORD's card, not the Bear) and
    // that separation is load-bearing here, not cosmetic: `modifiers.ts:158-176` collects from every
    // card ON THE BOARD carrying a modifier rule, so a modifier attached to Bear would be live
    // during the MTG11 replay at the bottom of this test and would silently move both Bears' Power.
    // Anthem Lord is never placed, so the replay sees exactly the fixture's own numbers.
    const anthemLordId = await addTemplate(router, user);

    // -- The ten rules — created as stubs first (so cross-rule references have something to point
    // at), then configured. Order of creation, captured by id:
    const boltRuleId = await addRule(router, user);
    const boltResolveId = await addRule(router, user);
    const counterMagicRuleId = await addRule(router, user);
    const lethalDamageId = await addRule(router, user);
    const blockId = await addRule(router, user);
    const modifierRuleId = await addRule(router, user);
    const returnToOwnerId = await addRule(router, user);
    const drawTwoInsteadId = await addRule(router, user);
    const oustId = await addRule(router, user);
    const setControllerRuleId = await addRule(router, user);

    // -- Bolt: trigger onCardPlayed (default) → announce Bolt (resolve) under the Stack window.
    // AC-adjacent: mtgish MTG1–MTG3.
    await goto(router, `/game/${GAME_ID}/rules/${boltRuleId}`);
    await screen.findByRole('heading', { level: 1 });
    await user.click(screen.getByRole('button', { name: 'Add an effect' }));
    await user.click(screen.getByRole('button', { name: 'Announce an action' }));
    await user.selectOptions(screen.getByRole('combobox', { name: 'Rule' }), boltResolveId);
    await user.selectOptions(screen.getByRole('combobox', { name: 'Priority window' }), windowStackId);
    expect(definition().ruleSets.find((r) => r.id === boltRuleId)!.effects).toEqual([
      { kind: 'announceAction', ruleId: boltResolveId, window: windowStackId },
    ]);

    // -- Bolt (resolve): reached only via the announce above — never fired by its own trigger, so
    // ponytail: the trigger field is left at its create-time default ('onCardPlayed') rather than
    // wiring up a `never_boltResolve`-style custom event. Both are inert for a rule that is neither
    // card-attached nor global (§5.1 — dispatch never scans it); mtgish.ts's naming convention is
    // documentation, not a behavioural requirement, and adding it here buys no extra construct
    // coverage. Every RuleSet-mode/trigger diff below therefore ignores `trigger` on resolve-only and
    // non-'trigger'-mode rules — this is snag (1) from the task brief, and this is the choice made.
    await goto(router, `/game/${GAME_ID}/rules/${boltResolveId}`);
    await screen.findByRole('heading', { level: 1 });
    await user.click(screen.getByRole('button', { name: 'Add an effect' }));
    await user.click(screen.getByRole('button', { name: 'Change a pool' }));
    await user.selectOptions(screen.getByRole('combobox', { name: 'Pool' }), lifeId);
    await user.click(screen.getByRole('button', { name: 'Whose' }));
    await user.click(screen.getByRole('radio', { name: /the next player/i }));
    await user.click(screen.getByRole('button', { name: 'Amount' }));
    const amt = within(screen.getByRole('dialog', { name: 'Amount' }));
    await user.clear(amt.getByRole('spinbutton', { name: 'Value' }));
    await user.type(amt.getByRole('spinbutton', { name: 'Value' }), '3');
    expect(definition().ruleSets.find((r) => r.id === boltResolveId)!.effects).toEqual([
      { kind: 'changePool', poolId: lifeId, seat: { kind: 'next' }, op: 'subtract', amount: { kind: 'literal', value: 3 } },
    ]);

    // -- Counter Magic: activation mode, perInstance, gated to the Stack window; counters the top
    // of the stack. The default effect from the picker already IS the fixture's shape.
    await goto(router, `/game/${GAME_ID}/rules/${counterMagicRuleId}`);
    await screen.findByRole('heading', { level: 1 });
    await user.click(screen.getByRole('radio', { name: 'activation' }));
    await user.selectOptions(screen.getByRole('combobox', { name: 'Priority window' }), windowStackId);
    await user.click(screen.getByRole('checkbox', { name: /a button on each card carrying this/i }));
    await user.click(screen.getByRole('button', { name: 'Add an effect' }));
    await user.click(screen.getByRole('button', { name: 'Counter an action' }));
    const counterMagicRule = () => definition().ruleSets.find((r) => r.id === counterMagicRuleId)!;
    expect(counterMagicRule().activation).toMatchObject({ window: windowStackId, perInstance: true, costCheck: null, cost: [] });
    expect(counterMagicRule().effects).toEqual([
      { kind: 'counterAction', action: { kind: 'action', ref: { kind: 'topOfStack' } } },
    ]);

    // -- Lethal Damage: continuous mode. condition: host's damage >= host's toughness. effect:
    // destroy every card in the Battlefield matching candidate's damage >= candidate's toughness.
    // AC-adjacent: MTG11.
    await goto(router, `/game/${GAME_ID}/rules/${lethalDamageId}`);
    await screen.findByRole('heading', { level: 1 });
    await user.click(screen.getByRole('radio', { name: 'continuous condition' }));
    await user.click(screen.getByRole('button', { name: /add a condition/i }));
    await user.click(ifBand().getByRole('button', { name: '+ condition' }));
    await setCardIndexRef(user, ifBand().getByRole('button', { name: 'Left side' }), /the card this is attached to/i, damageId);
    await user.selectOptions(ifBand().getByRole('combobox', { name: 'Comparison' }), '>=');
    await setCardIndexRef(user, ifBand().getByRole('button', { name: 'Right side' }), /the card this is attached to/i, toughnessId);

    await closePopovers(user);
    await user.click(screen.getByRole('button', { name: 'Add an effect' }));
    await user.click(screen.getByRole('button', { name: 'Destroy' }));
    await user.click(effectRow(1).getByRole('button', { name: 'Which cards' }));
    await user.click(screen.getByRole('radio', { name: /every card in a zone/i }));
    await user.selectOptions(screen.getByRole('combobox', { name: 'Zone' }), battlefieldId);
    // Popover is still open from the click above — the "cards matching a filter" radio is right
    // there in the same "Which cards" fieldset, no need to reopen (and reopening would just toggle
    // it shut, since `ChipPopover`'s trigger button is a plain open/close toggle).
    await user.click(screen.getByRole('radio', { name: /cards matching a filter/i }));
    const lethalWhere = () => effectRow(1).getByRole('group', { name: 'where' });
    await user.click(within(lethalWhere()).getByRole('button', { name: '+ condition' }));
    await setCardIndexRef(user, within(lethalWhere()).getByRole('button', { name: 'Left side' }), /the card under test/i, damageId);
    await user.selectOptions(within(lethalWhere()).getByRole('combobox', { name: 'Comparison' }), '>=');
    await setCardIndexRef(user, within(lethalWhere()).getByRole('button', { name: 'Right side' }), /the card under test/i, toughnessId);

    const lethalRule = () => definition().ruleSets.find((r) => r.id === lethalDamageId)!;
    expect(lethalRule().continuous).toBe(true);
    expect(lethalRule().condition).toEqual(
      oneCriteria({
        kind: 'criteria',
        left: { kind: 'cardIndex', card: { kind: 'host' }, indexId: damageId },
        op: '>=',
        right: { kind: 'cardIndex', card: { kind: 'host' }, indexId: toughnessId },
      })
    );
    expect(lethalRule().effects).toEqual([
      {
        kind: 'destroyCards',
        target: {
          kind: 'matching',
          from: { kind: 'allInZone', zone: { zoneId: battlefieldId, seat: null } },
          where: oneCriteria({
            kind: 'criteria',
            left: { kind: 'cardIndex', card: { kind: 'candidate' }, indexId: damageId },
            op: '>=',
            right: { kind: 'cardIndex', card: { kind: 'candidate' }, indexId: toughnessId },
          }),
        },
      },
    ]);
    // The bare shape mtgish.ts actually authors for the same construct — semantically identical.
    expect(mtg.lethalDamageRule.condition).toEqual({
      kind: 'criteria',
      left: { kind: 'cardIndex', card: { kind: 'host' }, indexId: mtg.DAMAGE },
      op: '>=',
      right: { kind: 'cardIndex', card: { kind: 'host' }, indexId: mtg.TOUGHNESS },
    });

    // -- Declare Block: onZoneEnter. attach the entering (triggering) card to the top of the
    // Battlefield; both cards take the other's power as damage. AC-adjacent: MTG11.
    await goto(router, `/game/${GAME_ID}/rules/${blockId}`);
    await screen.findByRole('heading', { level: 1 });
    await user.selectOptions(screen.getByRole('combobox', { name: 'Trigger' }), 'onZoneEnter');

    await user.click(screen.getByRole('button', { name: 'Add an effect' }));
    await user.click(screen.getByRole('button', { name: 'Attach' }));
    await user.click(effectRow(1).getByRole('button', { name: 'Attach to' }));
    await user.click(screen.getByRole('radio', { name: /the top card of a zone/i }));
    await user.selectOptions(screen.getByRole('combobox', { name: 'Zone' }), battlefieldId);

    await closePopovers(user);
    await user.click(screen.getByRole('button', { name: 'Add an effect' }));
    await user.click(screen.getByRole('button', { name: 'Change a card number' }));
    await user.selectOptions(effectRow(2).getByRole('combobox', { name: 'Card number' }), damageId);
    await user.selectOptions(effectRow(2).getByRole('combobox', { name: 'Operation' }), 'add');
    await setCardIndexRef(user, effectRow(2).getByRole('button', { name: 'Amount' }), /the card this is attached to/i, powerId);

    await closePopovers(user);
    await user.click(screen.getByRole('button', { name: 'Add an effect' }));
    await user.click(screen.getByRole('button', { name: 'Change a card number' }));
    await user.click(effectRow(3).getByRole('button', { name: 'Which cards' }));
    await user.click(screen.getByRole('radio', { name: /the card another card is attached to/i }));
    await user.selectOptions(effectRow(3).getByRole('combobox', { name: 'Card number' }), damageId);
    await user.selectOptions(effectRow(3).getByRole('combobox', { name: 'Operation' }), 'add');
    await setCardIndexRef(user, effectRow(3).getByRole('button', { name: 'Amount' }), /^this card$/i, powerId);

    const blockRule = () => definition().ruleSets.find((r) => r.id === blockId)!;
    expect(blockRule().trigger).toBe('onZoneEnter');
    expect(blockRule().effects).toEqual([
      { kind: 'attach', target: { kind: 'triggeringCard' }, host: { kind: 'zoneTop', zone: { zoneId: battlefieldId, seat: null } } },
      {
        kind: 'setCardIndex',
        target: { kind: 'triggeringCard' },
        indexId: damageId,
        op: 'add',
        amount: { kind: 'cardIndex', card: { kind: 'host' }, indexId: powerId },
      },
      {
        kind: 'setCardIndex',
        target: { kind: 'hostOf', card: { kind: 'triggering' } },
        indexId: damageId,
        op: 'add',
        amount: { kind: 'cardIndex', card: { kind: 'triggering' }, indexId: powerId },
      },
    ]);

    // -- Modifier rule: value-modifier mode — mtgish's `anthemLordRule`, an anthem over every tagged
    // creature on the Battlefield, live only while its own source sits there. AC-adjacent: MTG6.
    // NOT MTG7: that criterion is specifically "every `set` applies before every `adjust`", which is
    // §5.4's algorithm rather than an authoring shape, needs a second `op:'set'` modifier to observe
    // at all, and is already proven headlessly by `modifiers.test.ts` / the `powerSetRule` pairing.
    // `indexId`/`op`/`amount` are the mode-switch's own defaults (`RuleSetEditor.tsx:127-133`) and
    // coincide with the fixture, the same way Counter Magic's effect picker default does — so the
    // three fields DRIVEN here (scope kind, its zone and tag, and `activeZones`) are what make this
    // more than a read-back of that patch.
    await goto(router, `/game/${GAME_ID}/rules/${modifierRuleId}`);
    await screen.findByRole('heading', { level: 1 });
    await user.click(screen.getByRole('radio', { name: 'value modifier' }));
    await user.click(screen.getByRole('button', { name: 'Which cards are modified' }));
    await user.click(screen.getByRole('radio', { name: /cards with a tag, in a zone/i }));
    await user.selectOptions(screen.getByRole('combobox', { name: 'Zone' }), battlefieldId);
    await user.type(screen.getByRole('textbox', { name: 'Tag' }), 'creature');
    await closePopovers(user);
    // "Applies while its source is in" labels its checkboxes with the zone's own name; zones are
    // never renamed in this trim, so the name is read back rather than spelled out.
    const battlefieldName = definition().zones.find((z) => z.id === battlefieldId)!.name;
    await user.click(screen.getByRole('checkbox', { name: battlefieldName }));

    const modifierRule = () => definition().ruleSets.find((r) => r.id === modifierRuleId)!;
    expect(modifierRule().modifier).toEqual({
      scope: { kind: 'taggedInZone', zone: { zoneId: battlefieldId, seat: null }, tag: 'creature' },
      indexId: powerId,
      op: 'adjust',
      amount: { kind: 'literal', value: 1 },
      activeZones: [battlefieldId],
    });
    expect(modifierRule()).toMatchObject({ continuous: false, replaces: null, activation: null });
    // The same construct as mtgish.ts authors it — field for field, ids aside.
    expect(mtg.anthemLordRule.modifier).toEqual({
      scope: { kind: 'taggedInZone', zone: { zoneId: mtg.MTG_BATTLEFIELD, seat: null }, tag: mtg.MTG_CREATURE_TAG },
      indexId: mtg.MTG_POWER,
      op: 'adjust',
      amount: { kind: 'literal', value: 1 },
      activeZones: [mtg.MTG_BATTLEFIELD],
    });

    // -- Return to Owner: activation, global, no cost, no window (every default matches) — moves
    // every card on the Battlefield to the OWNER of the top card's Hand. AC-adjacent: MTG8, SP5.
    await goto(router, `/game/${GAME_ID}/rules/${returnToOwnerId}`);
    await screen.findByRole('heading', { level: 1 });
    await user.click(screen.getByRole('radio', { name: 'activation' }));
    await user.click(screen.getByRole('checkbox', { name: /game-level rule/i }));

    await user.click(screen.getByRole('button', { name: 'Add an effect' }));
    await user.click(screen.getByRole('button', { name: 'Move' }));
    await user.click(effectRow(1).getByRole('button', { name: 'Which cards' }));
    await user.click(screen.getByRole('radio', { name: /every card in a zone/i }));
    await user.selectOptions(screen.getByRole('combobox', { name: 'Zone' }), battlefieldId);
    await closePopovers(user);
    await user.click(effectRow(1).getByRole('button', { name: 'Destination zone' }));
    await user.selectOptions(screen.getByRole('combobox', { name: 'Zone' }), handId);
    await user.click(screen.getByRole('button', { name: 'Owned by' }));
    await user.click(screen.getByRole('radio', { name: /a card's owner/i }));
    await user.click(screen.getByRole('button', { name: 'Of which card' }));
    // Nested inside "Destination zone" (never closed — it is still showing Hand) which is itself
    // still showing its own "Zone" select, so this one is scoped to its own dialog explicitly.
    const ofWhichCard = within(screen.getByRole('dialog', { name: 'Of which card' }));
    await user.click(ofWhichCard.getByRole('radio', { name: /the top card of a zone/i }));
    await user.selectOptions(ofWhichCard.getByRole('combobox', { name: 'Zone' }), battlefieldId);

    const returnToOwnerRule = () => definition().ruleSets.find((r) => r.id === returnToOwnerId)!;
    expect(definition().globalRuleSetIds).toContain(returnToOwnerId);
    expect(returnToOwnerRule().activation).toMatchObject({ costCheck: null, cost: [], window: null, perInstance: false });
    expect(returnToOwnerRule().effects).toEqual([
      {
        kind: 'moveCards',
        target: { kind: 'allInZone', zone: { zoneId: battlefieldId, seat: null } },
        to: { zoneId: handId, seat: { kind: 'owner', card: { kind: 'zoneTop', zone: { zoneId: battlefieldId, seat: null } } } },
        position: 'top',
      },
    ]);

    // -- Draw Two Instead: replacement mode. effectKind/match default to exactly the fixture's
    // shape (drawCards, match:null) — only the payload effect needs configuring. AC-adjacent: MTG10.
    await goto(router, `/game/${GAME_ID}/rules/${drawTwoInsteadId}`);
    await screen.findByRole('heading', { level: 1 });
    await user.click(screen.getByRole('radio', { name: 'replacement' }));
    await user.click(screen.getByRole('checkbox', { name: /game-level rule/i }));

    await user.click(screen.getByRole('button', { name: 'Add an effect' }));
    await user.click(screen.getByRole('button', { name: 'Draw' }));
    await user.click(effectRow(1).getByRole('button', { name: 'Source zone' }));
    await user.selectOptions(screen.getByRole('combobox', { name: 'Zone' }), libraryId);
    await user.click(screen.getByRole('button', { name: 'Owned by' }));
    await user.click(screen.getByRole('radio', { name: /the player who played this/i }));
    await closePopovers(user);
    await user.click(effectRow(1).getByRole('button', { name: 'Destination zone' }));
    await user.selectOptions(screen.getByRole('combobox', { name: 'Zone' }), handId);
    await user.click(screen.getByRole('button', { name: 'Owned by' }));
    await user.click(screen.getByRole('radio', { name: /the player who played this/i }));
    await user.click(effectRow(1).getByRole('button', { name: 'How many cards' }));
    const count = within(screen.getByRole('dialog', { name: 'How many cards' }));
    await user.clear(count.getByRole('spinbutton', { name: 'Value' }));
    await user.type(count.getByRole('spinbutton', { name: 'Value' }), '2');

    const drawTwoRule = () => definition().ruleSets.find((r) => r.id === drawTwoInsteadId)!;
    expect(definition().globalRuleSetIds).toContain(drawTwoInsteadId);
    expect(drawTwoRule().replaces).toEqual({ effectKind: 'drawCards', match: null });
    expect(drawTwoRule().effects).toEqual([
      {
        kind: 'drawCards',
        from: { zoneId: libraryId, seat: { kind: 'triggeringSeat' } },
        to: { zoneId: handId, seat: { kind: 'triggeringSeat' } },
        count: { kind: 'literal', value: 2 },
      },
    ]);

    // -- Oust: continuous, global — eliminates seat 0 at zero life. AC-adjacent: MTG9, SP11.
    await goto(router, `/game/${GAME_ID}/rules/${oustId}`);
    await screen.findByRole('heading', { level: 1 });
    await user.click(screen.getByRole('radio', { name: 'continuous condition' }));
    await user.click(screen.getByRole('checkbox', { name: /game-level rule/i }));
    await user.click(screen.getByRole('button', { name: /add a condition/i }));
    await user.click(ifBand().getByRole('button', { name: '+ condition' }));
    await user.click(ifBand().getByRole('button', { name: 'Left side' }));
    await user.click(screen.getByRole('radio', { name: 'A pool' }));
    await user.selectOptions(screen.getByRole('combobox', { name: 'Pool' }), lifeId);
    await user.click(screen.getByRole('button', { name: 'Of' }));
    await user.click(screen.getByRole('radio', { name: /a specific seat/i }));
    await user.selectOptions(ifBand().getByRole('combobox', { name: 'Comparison' }), '<=');

    await closePopovers(user);
    await user.click(screen.getByRole('button', { name: 'Add an effect' }));
    await user.click(screen.getByRole('button', { name: 'Eliminate a player' }));
    await user.click(effectRow(1).getByRole('button', { name: 'Which player' }));
    await user.click(screen.getByRole('radio', { name: /a specific seat/i }));

    const oustRule = () => definition().ruleSets.find((r) => r.id === oustId)!;
    expect(definition().globalRuleSetIds).toContain(oustId);
    expect(oustRule().continuous).toBe(true);
    expect(oustRule().condition).toEqual(
      oneCriteria({
        kind: 'criteria',
        left: { kind: 'pool', poolId: lifeId, seat: { kind: 'seat', index: 0 } },
        op: '<=',
        right: { kind: 'literal', value: 0 },
      })
    );
    expect(oustRule().effects).toEqual([{ kind: 'eliminateSeat', seat: { kind: 'seat', index: 0 } }]);

    // -- Set Controller rule: the default "Change control" effect already matches — a bare
    // triggeringCard/active setController, global. AC-adjacent: SP5.
    await goto(router, `/game/${GAME_ID}/rules/${setControllerRuleId}`);
    await screen.findByRole('heading', { level: 1 });
    await user.click(screen.getByRole('checkbox', { name: /game-level rule/i }));
    await user.click(screen.getByRole('button', { name: 'Add an effect' }));
    await user.click(screen.getByRole('button', { name: 'Change control' }));
    const setControllerRule = () => definition().ruleSets.find((r) => r.id === setControllerRuleId)!;
    expect(setControllerRule().effects).toEqual([
      { kind: 'setController', target: { kind: 'triggeringCard' }, seat: { kind: 'active' } },
    ]);

    // -- Attach rules to Bear and Bolt/Counter Magic through the card editor's checkboxes.
    await goto(router, `/game/${GAME_ID}/cards/${bearId}`);
    await screen.findByRole('heading', { level: 1 });
    for (const name of ['New rule 4', 'New rule 5']) {
      await user.click(screen.getByRole('checkbox', { name }));
    }
    expect(definition().templates.find((t) => t.id === bearId)!.ruleSetIds).toEqual([
      lethalDamageId,
      blockId,
    ]);

    await goto(router, `/game/${GAME_ID}/cards/${anthemLordId}`);
    await screen.findByRole('heading', { level: 1 });
    await user.click(screen.getByRole('checkbox', { name: 'New rule 6' }));
    expect(definition().templates.find((t) => t.id === anthemLordId)!.ruleSetIds).toEqual([modifierRuleId]);

    await goto(router, `/game/${GAME_ID}/cards/${boltId}`);
    await screen.findByRole('heading', { level: 1 });
    await user.click(screen.getByRole('checkbox', { name: 'New rule' }));
    expect(definition().templates.find((t) => t.id === boltId)!.ruleSetIds).toEqual([boltRuleId]);

    await goto(router, `/game/${GAME_ID}/cards/${counterMagicId}`);
    await screen.findByRole('heading', { level: 1 });
    await user.click(screen.getByRole('checkbox', { name: 'New rule 3' }));
    expect(definition().templates.find((t) => t.id === counterMagicId)!.ruleSetIds).toEqual([counterMagicRuleId]);

    // ==========================================================================================
    // Export -> import -> play. §7.2's harness, reused rather than rebuilt.
    // ==========================================================================================
    const authored = definition();
    const json = exportJson(authored);
    const imported = importJson(json);
    expect(imported.ok).toBe(true);
    if (!imported.ok) return;
    // §7.2's own trap: a wrongly-`.optional()` field only shows on the SECOND round trip.
    expect(exportJson(imported.definition)).toBe(json);

    const def = imported.definition;

    // (b) "Plays identically to the corresponding TypeScript fixture" — mtgish.ts's own MTG11
    // scenario (attach a blocker, both Bears meet lethal damage), replayed against the ROUND-
    // TRIPPED, re-authored definition rather than the hand-written fixture. AC-adjacent: MTG11,
    // same outcome as the "behavioral" case fixtures.test.ts already proves for the real mtgish —
    // this file is deliberately not that criterion's traceability tag (see the file header), just
    // corroboration that the re-authored construct behaves the same way.
    const state = emptyBoard(def);
    const attackerId = place(state, def, battlefieldId, bearId, 'atk');
    const blockerId = place(state, def, `${handId}#1`, bearId, 'blk');
    const lines: LogLine[] = [];
    let result = step(
      state,
      { kind: 'action', action: { kind: 'moveCard', cardId: blockerId, to: { zoneId: battlefieldId, seat: null }, position: 'bottom' }, override: false },
      lines,
      def
    );
    let guard = 0;
    while (!result.done) {
      if (++guard > 10_000) throw new Error('runaway');
      result = step(state, CONTINUE, lines, def);
    }
    expect(state.cards[attackerId]).toBeUndefined();
    expect(state.cards[blockerId]).toBeUndefined();
    expect(lines.some((l) => l.ruleId === lethalDamageId)).toBe(true);
  }, 30_000);
});

// ============================================================================================
// vtesish
// ============================================================================================

describe('vtesish, re-authored through the UI', () => {
  it('exports, imports, and plays like the corresponding constructs in vtesish.ts', async () => {
    await seed(5);
    const { router, user } = openGame();

    // -- Pools: POOL and one single-sided vote total (VOTES_FOR / VOTES_FOR_TOTAL), enough to prove
    // `sum` (SP6) without rebuilding V6/V7's whole pass/fail referendum — that behaviour is already
    // proven headlessly in `fixtures.test.ts`; this is a construct-authorability proof.
    await screen.findByRole('button', { name: 'Add pool' });
    await user.click(screen.getByRole('button', { name: 'Add pool' })); // POOL
    const poolId = definition().pools[0].id;
    await user.type(screen.getByRole('spinbutton', { name: 'Starting value' }), '30');
    await user.type(screen.getByRole('spinbutton', { name: 'Minimum' }), '0');
    await user.type(screen.getByRole('spinbutton', { name: 'Maximum' }), '30');

    await user.click(screen.getByRole('button', { name: 'Add pool' })); // Votes For
    const votesForId = definition().pools[1].id;
    await user.type(screen.getByRole('spinbutton', { name: 'Maximum' }), '10');

    await user.click(screen.getByRole('button', { name: 'Add pool' })); // Votes For Total — game scope
    const votesForTotalId = definition().pools[2].id;
    await user.selectOptions(screen.getByRole('combobox', { name: 'Scope' }), 'game');
    await user.type(screen.getByRole('spinbutton', { name: 'Maximum' }), '50');

    // -- Zones — §9.3's four.
    await goto(router, `/game/${GAME_ID}/zones`);
    await user.click(await screen.findByRole('button', { name: 'Add zone' })); // Uncontrolled
    const uncontrolledId = definition().zones[0].id;
    await user.selectOptions(screen.getByRole('combobox', { name: 'Layout' }), 'row');
    await user.click(screen.getByRole('checkbox', { name: 'Ordered' }));

    await user.click(screen.getByRole('button', { name: 'Add zone' })); // Ready
    const readyZoneId = definition().zones[1].id;
    await user.selectOptions(screen.getByRole('combobox', { name: 'Layout' }), 'row');
    await user.click(screen.getByRole('checkbox', { name: 'Ordered' }));

    await user.click(screen.getByRole('button', { name: 'Add zone' })); // Library
    const libraryId = definition().zones[2].id;
    await user.selectOptions(screen.getByRole('combobox', { name: 'Visibility' }), 'faceDown');
    // Not referenced by any rule in this trim (deals happen through setup, not an authored rule) —
    // asserted to exist rather than silently dropped.
    expect(definition().zones.find((z) => z.id === libraryId)).toMatchObject({ visibility: 'faceDown' });

    await user.click(screen.getByRole('button', { name: 'Add zone' })); // Hand
    const handId = definition().zones[3].id;
    await user.selectOptions(screen.getByRole('combobox', { name: 'Visibility' }), 'ownerOnly');
    await user.selectOptions(screen.getByRole('combobox', { name: 'Layout' }), 'fan');

    // -- Priority window — WINDOW_BLOCK: the one place either fixture authors NON-default window
    // fields (start:'controllerOfAction', includeStart:false).
    await goto(router, `/game/${GAME_ID}/priority`);
    await user.click(await screen.findByRole('button', { name: 'Add window' }));
    const windowBlockId = definition().priorityWindows[0].id;
    await user.selectOptions(screen.getByRole('combobox', { name: 'Poll starts at' }), 'controllerOfAction');
    await user.click(screen.getByRole('checkbox', { name: /include the starting seat/i }));
    // The (b2) replay below passes priority unconditionally until `done`, so it comes out the same
    // whichever seat the poll starts at — these two fields are proven HERE, against the fixture's
    // own literals, or nowhere. `direction`/`passesToClose` are add-time defaults that happen to
    // match, asserted alongside so a control writing the wrong field of the same shape is caught.
    expect(definition().priorityWindows[0]).toMatchObject({
      start: 'controllerOfAction',
      direction: 'forward',
      includeStart: false,
      passesToClose: null,
    });
    expect(vtes.windowBlock).toMatchObject({
      start: 'controllerOfAction',
      direction: 'forward',
      includeStart: false,
      passesToClose: null,
    });

    // -- Events: onUntap (V11) and onReferendumClose (the votes rule's trigger).
    await goto(router, `/game/${GAME_ID}/events`);
    await user.type(screen.getByRole('textbox', { name: 'New event' }), 'onUntap');
    await user.click(screen.getByRole('button', { name: 'Add event' }));
    await user.type(screen.getByRole('textbox', { name: 'New event' }), 'onReferendumClose');
    await user.click(screen.getByRole('button', { name: 'Add event' }));
    expect(definition().customEvents).toEqual(['onUntap', 'onReferendumClose']);

    // -- Templates + their card indexes.
    const minionId = await addTemplate(router, user); // INFLUENCE, CAPACITY (V11), DISCIPLINE (V8-adjacent)
    await user.type(screen.getByRole('textbox', { name: 'Tags' }), 'minion');
    await user.click(screen.getByRole('button', { name: /add a number/i }));
    let names = screen.getAllByRole('textbox', { name: 'Name' });
    await user.clear(names[0]);
    await user.type(names[0], 'Influence');

    await user.click(screen.getByRole('button', { name: /add a number/i }));
    names = screen.getAllByRole('textbox', { name: 'Name' });
    await user.clear(names[1]);
    await user.type(names[1], 'Capacity');
    const starts = screen.getAllByRole('spinbutton', { name: 'Starting value' });
    await user.type(starts[1], '3');

    await user.click(screen.getByRole('button', { name: /add a number/i }));
    names = screen.getAllByRole('textbox', { name: 'Name' });
    await user.clear(names[2]);
    await user.type(names[2], 'Discipline');

    const [influenceId, capacityId, disciplineId] = definition()
      .templates.find((t) => t.id === minionId)!
      .indexes.map((i) => i.id);

    const actionCardId = await addTemplate(router, user);
    const strikeId = await addTemplate(router, user);
    const equipmentId = await addTemplate(router, user);

    // -- The eight rules, stubbed first.
    const actionRuleId = await addRule(router, user);
    const actionResolveId = await addRule(router, user);
    const tickId = await addRule(router, user);
    const readyId = await addRule(router, user);
    const tallyId = await addRule(router, user);
    const strikeRuleId = await addRule(router, user);
    const strikeResolveId = await addRule(router, user);
    const equipmentRuleId = await addRule(router, user);

    // -- Predator's Claim: announces the resolve rule under the Block window. AC-adjacent: V1/V3/V4.
    await goto(router, `/game/${GAME_ID}/rules/${actionRuleId}`);
    await screen.findByRole('heading', { level: 1 });
    await user.click(screen.getByRole('button', { name: 'Add an effect' }));
    await user.click(screen.getByRole('button', { name: 'Announce an action' }));
    await user.selectOptions(screen.getByRole('combobox', { name: 'Rule' }), actionResolveId);
    await user.selectOptions(screen.getByRole('combobox', { name: 'Priority window' }), windowBlockId);
    expect(definition().ruleSets.find((r) => r.id === actionRuleId)!.effects).toEqual([
      { kind: 'announceAction', ruleId: actionResolveId, window: windowBlockId },
    ]);

    // -- Predator's Claim (resolve): charges the PREDATOR of the triggering card's OWNER —
    // `relative(from: owner(card: triggering), offset: -1)`. AC-adjacent: V1.
    await goto(router, `/game/${GAME_ID}/rules/${actionResolveId}`);
    await screen.findByRole('heading', { level: 1 });
    await user.click(screen.getByRole('button', { name: 'Add an effect' }));
    await user.click(screen.getByRole('button', { name: 'Change a pool' }));
    await user.selectOptions(screen.getByRole('combobox', { name: 'Pool' }), poolId);
    await user.selectOptions(screen.getByRole('combobox', { name: 'Operation' }), 'subtract');
    await user.click(screen.getByRole('button', { name: 'Whose' }));
    await user.click(screen.getByRole('radio', { name: /counted from another player/i }));
    // ponytail: `user.type` keystroke-by-keystroke chokes on `<input type="number">` mid-typing a
    // lone "-" — jsdom reports `.value` as "" for the not-yet-a-number state, which the controlled
    // NumberField reads as "cleared" and commits 0, wiping the sign before "1" lands. One `fireEvent`
    // sidesteps the same jsdom quirk `InlineNumber`'s own draft-state comment already documents for
    // the sibling component; not the phase-4 authoring UI, so not fixed here.
    fireEvent.change(screen.getByRole('spinbutton', { name: 'Seats along' }), { target: { value: '-1' } });
    const countedFrom = within(screen.getByRole('group', { name: 'Counted from' }));
    await user.click(countedFrom.getByRole('radio', { name: /a card's owner/i }));

    const actionResolveRule = () => definition().ruleSets.find((r) => r.id === actionResolveId)!;
    expect(actionResolveRule().effects).toEqual([
      {
        kind: 'changePool',
        poolId,
        seat: { kind: 'relative', from: { kind: 'owner', card: { kind: 'triggering' } }, offset: -1 },
        op: 'subtract',
        amount: { kind: 'literal', value: 1 },
      },
    ]);

    // -- Tick Influence / Ready When Influenced: pure v1 primitives, driven by onUntap, global.
    // AC-adjacent: V11.
    await goto(router, `/game/${GAME_ID}/rules/${tickId}`);
    await screen.findByRole('heading', { level: 1 });
    await user.selectOptions(screen.getByRole('combobox', { name: 'Trigger' }), 'onUntap');
    await user.click(screen.getByRole('checkbox', { name: /game-level rule/i }));
    await user.type(screen.getByRole('spinbutton', { name: 'Priority' }), '1');
    await user.click(screen.getByRole('button', { name: 'Add an effect' }));
    await user.click(screen.getByRole('button', { name: 'Change a card number' }));
    await user.click(effectRow(1).getByRole('button', { name: 'Which cards' }));
    await user.click(screen.getByRole('radio', { name: /every card in a zone/i }));
    await user.selectOptions(screen.getByRole('combobox', { name: 'Zone' }), uncontrolledId);
    await user.click(screen.getByRole('button', { name: 'Owned by' }));
    await user.click(screen.getByRole('radio', { name: /the player who played this/i }));
    await user.selectOptions(effectRow(1).getByRole('combobox', { name: 'Card number' }), influenceId);
    await user.selectOptions(effectRow(1).getByRole('combobox', { name: 'Operation' }), 'add');

    const tickRule = () => definition().ruleSets.find((r) => r.id === tickId)!;
    expect(definition().globalRuleSetIds).toContain(tickId);
    expect(tickRule().effects).toEqual([
      {
        kind: 'setCardIndex',
        target: { kind: 'allInZone', zone: { zoneId: uncontrolledId, seat: { kind: 'triggeringSeat' } } },
        indexId: influenceId,
        op: 'add',
        amount: { kind: 'literal', value: 1 },
      },
    ]);

    await goto(router, `/game/${GAME_ID}/rules/${readyId}`);
    await screen.findByRole('heading', { level: 1 });
    await user.selectOptions(screen.getByRole('combobox', { name: 'Trigger' }), 'onUntap');
    await user.click(screen.getByRole('checkbox', { name: /game-level rule/i }));
    await user.click(screen.getByRole('button', { name: 'Add an effect' }));
    await user.click(screen.getByRole('button', { name: 'Move' }));
    await user.click(effectRow(1).getByRole('button', { name: 'Which cards' }));
    await user.click(screen.getByRole('radio', { name: /every card in a zone/i }));
    await user.selectOptions(screen.getByRole('combobox', { name: 'Zone' }), uncontrolledId);
    await user.click(screen.getByRole('button', { name: 'Owned by' }));
    await user.click(screen.getByRole('radio', { name: /the player who played this/i }));
    // "Which cards" popover is still open from above — see the identical note on Lethal Damage.
    await user.click(screen.getByRole('radio', { name: /cards matching a filter/i }));
    const readyWhere = () => effectRow(1).getByRole('group', { name: 'where' });
    await user.click(within(readyWhere()).getByRole('button', { name: '+ condition' }));
    await setCardIndexRef(user, within(readyWhere()).getByRole('button', { name: 'Left side' }), /the card under test/i, influenceId);
    await user.selectOptions(within(readyWhere()).getByRole('combobox', { name: 'Comparison' }), '>=');
    await setCardIndexRef(user, within(readyWhere()).getByRole('button', { name: 'Right side' }), /the card under test/i, capacityId);
    await closePopovers(user);
    await user.click(effectRow(1).getByRole('button', { name: 'Destination zone' }));
    await user.selectOptions(screen.getByRole('combobox', { name: 'Zone' }), readyZoneId);
    await user.click(screen.getByRole('button', { name: 'Owned by' }));
    await user.click(screen.getByRole('radio', { name: /the player who played this/i }));

    const readyRule = () => definition().ruleSets.find((r) => r.id === readyId)!;
    expect(definition().globalRuleSetIds).toContain(readyId);
    expect(readyRule().effects).toEqual([
      {
        kind: 'moveCards',
        target: {
          kind: 'matching',
          from: { kind: 'allInZone', zone: { zoneId: uncontrolledId, seat: { kind: 'triggeringSeat' } } },
          where: oneCriteria({
            kind: 'criteria',
            left: { kind: 'cardIndex', card: { kind: 'candidate' }, indexId: influenceId },
            op: '>=',
            right: { kind: 'cardIndex', card: { kind: 'candidate' }, indexId: capacityId },
          }),
        },
        to: { zoneId: readyZoneId, seat: { kind: 'triggeringSeat' } },
        position: 'top',
      },
    ]);
    // The bare shape vtesish.ts authors for the analogous "candidate meets threshold" filter.
    expect(vtes.readyRule.effects[0]).toMatchObject({
      target: {
        kind: 'matching',
        where: {
          kind: 'criteria',
          left: { kind: 'cardIndex', card: { kind: 'candidate' }, indexId: vtes.INFLUENCE },
          op: '>=',
          right: { kind: 'cardIndex', card: { kind: 'candidate' }, indexId: vtes.CAPACITY },
        },
      },
    });

    // -- Tally Votes: `sum` (SP6), both as a condition operand and as the effect's amount.
    await goto(router, `/game/${GAME_ID}/rules/${tallyId}`);
    await screen.findByRole('heading', { level: 1 });
    await user.selectOptions(screen.getByRole('combobox', { name: 'Trigger' }), 'onReferendumClose');
    await user.click(screen.getByRole('checkbox', { name: /game-level rule/i }));
    await user.click(screen.getByRole('button', { name: /add a condition/i }));
    await user.click(ifBand().getByRole('button', { name: '+ condition' }));
    await user.click(ifBand().getByRole('button', { name: 'Left side' }));
    await user.click(screen.getByRole('radio', { name: 'A pool' }));
    await user.selectOptions(screen.getByRole('combobox', { name: 'Pool' }), votesForId);
    await user.click(screen.getByRole('button', { name: 'Of' }));
    await user.click(screen.getByRole('radio', { name: /all players, summed/i }));

    await closePopovers(user);
    await user.click(screen.getByRole('button', { name: 'Add an effect' }));
    await user.click(screen.getByRole('button', { name: 'Change a pool' }));
    await user.selectOptions(effectRow(1).getByRole('combobox', { name: 'Pool' }), votesForTotalId);
    await user.selectOptions(effectRow(1).getByRole('combobox', { name: 'Operation' }), 'set');
    await user.click(effectRow(1).getByRole('button', { name: 'Amount' }));
    // Scoped to its own dialog — the effect's own "Pool" select (votesForTotalId, the destination)
    // is inline in the sentence, not behind a popover, and stays visible the whole time.
    const amountDialog = within(screen.getByRole('dialog', { name: 'Amount' }));
    await user.click(amountDialog.getByRole('radio', { name: 'A pool' }));
    await user.selectOptions(amountDialog.getByRole('combobox', { name: 'Pool' }), votesForId);
    await user.click(amountDialog.getByRole('button', { name: 'Of' }));
    await user.click(screen.getByRole('radio', { name: /all players, summed/i }));

    const tallyRule = () => definition().ruleSets.find((r) => r.id === tallyId)!;
    expect(definition().globalRuleSetIds).toContain(tallyId);
    expect(tallyRule().condition).toEqual(
      oneCriteria({
        kind: 'criteria',
        left: { kind: 'pool', poolId: votesForId, seat: { kind: 'all', quantifier: 'sum' } },
        op: '=',
        right: { kind: 'literal', value: 0 },
      })
    );
    expect(tallyRule().effects).toEqual([
      {
        kind: 'changePool',
        poolId: votesForTotalId,
        seat: null,
        op: 'set',
        amount: { kind: 'pool', poolId: votesForId, seat: { kind: 'all', quantifier: 'sum' } },
      },
    ]);

    // -- Strike / Strike (resolve): sealedChoice, the one v2 effect kind mtgish's trim does not use.
    // AC-adjacent: V5.
    await goto(router, `/game/${GAME_ID}/rules/${strikeRuleId}`);
    await screen.findByRole('heading', { level: 1 });
    await user.click(screen.getByRole('button', { name: 'Add an effect' }));
    await user.click(screen.getByRole('button', { name: 'Announce an action' }));
    await user.selectOptions(screen.getByRole('combobox', { name: 'Rule' }), strikeResolveId);
    expect(definition().ruleSets.find((r) => r.id === strikeRuleId)!.effects).toEqual([
      { kind: 'announceAction', ruleId: strikeResolveId, window: null },
    ]);

    await goto(router, `/game/${GAME_ID}/rules/${strikeResolveId}`);
    await screen.findByRole('heading', { level: 1 });
    await user.click(screen.getByRole('button', { name: 'Add an effect' }));
    await user.click(screen.getByRole('button', { name: 'Sealed choice' }));
    await user.type(effectRow(1).getByRole('textbox', { name: 'Choice key' }), 'strike');
    const options = within(screen.getByRole('list', { name: 'Options' }));
    await user.click(screen.getByRole('button', { name: '+ option' }));
    await user.type(options.getByRole('textbox', { name: 'Option 1 id' }), 'hit');
    await user.type(options.getByRole('textbox', { name: 'Option 1 label' }), 'Hit');
    await user.click(screen.getByRole('button', { name: '+ option' }));
    await user.type(options.getByRole('textbox', { name: 'Option 2 id' }), 'dodge');
    await user.type(options.getByRole('textbox', { name: 'Option 2 label' }), 'Dodge');

    const strikeResolveRule = () => definition().ruleSets.find((r) => r.id === strikeResolveId)!;
    expect(strikeResolveRule().effects).toEqual([
      {
        kind: 'sealedChoice',
        choiceId: 'strike',
        seats: { kind: 'all' },
        options: [
          { id: 'hit', label: 'Hit' },
          { id: 'dodge', label: 'Dodge' },
        ],
      },
    ]);

    // -- Use Equipment: activation with a cost check on the HOST's discipline. This is snag (3) —
    // §5.6's own group-wrapping of `condition` also happens to `activation.costCheck`, the first
    // time the store ever sees it: `CriteriaGroupEditor` always writes a `{kind:'group', ...}`
    // wrapper, even though vtesish.ts's own `costCheck` is a bare `{kind:'criteria', ...}` — the
    // group of one is semantically identical (an AND of one child is that child), but it is NOT
    // byte-identical to the fixture's hand-written shape. Asserted deliberately, not normalised away.
    await goto(router, `/game/${GAME_ID}/rules/${equipmentRuleId}`);
    await screen.findByRole('heading', { level: 1 });
    await user.click(screen.getByRole('radio', { name: 'activation' }));
    await user.click(screen.getByRole('checkbox', { name: /a button on each card carrying this/i }));
    const costCheck = within(screen.getByRole('group', { name: 'Cost check' }));
    await user.click(costCheck.getByRole('button', { name: '+ condition' }));
    await setCardIndexRef(user, costCheck.getByRole('button', { name: 'Left side' }), /the card this is attached to/i, disciplineId);
    await user.selectOptions(costCheck.getByRole('combobox', { name: 'Comparison' }), '>=');
    await user.click(costCheck.getByRole('button', { name: 'Right side' }));
    const rightVal = within(screen.getByRole('dialog', { name: 'Right side' }));
    await user.clear(rightVal.getByRole('spinbutton', { name: 'Value' }));
    await user.type(rightVal.getByRole('spinbutton', { name: 'Value' }), '2');

    const equipmentRule = () => definition().ruleSets.find((r) => r.id === equipmentRuleId)!;
    // §5.8/§9.3 confirm — "cost:[]", so nothing here is blocked by the unfiltered activation-cost
    // picker (snag (2)): this rule has no cost effects at all, only a cost CHECK.
    expect(equipmentRule().activation).toMatchObject({ perInstance: true, cost: [] });
    expect(equipmentRule().activation?.costCheck).toEqual({
      kind: 'group',
      combinator: 'and',
      children: [
        {
          kind: 'criteria',
          left: { kind: 'cardIndex', card: { kind: 'host' }, indexId: disciplineId },
          op: '>=',
          right: { kind: 'literal', value: 2 },
        },
      ],
    });
    // The equivalent bare shape vtesish.ts actually authors — proven semantically identical
    // (AND-of-one), not structurally identical, which is the whole point of this snag.
    expect(vtes.equipmentAbilityRule.activation?.costCheck).toEqual({
      kind: 'criteria',
      left: { kind: 'cardIndex', card: { kind: 'host' }, indexId: vtes.DISCIPLINE },
      op: '>=',
      right: { kind: 'literal', value: 2 },
    });

    // -- Attach rules to their cards.
    await goto(router, `/game/${GAME_ID}/cards/${actionCardId}`);
    await screen.findByRole('heading', { level: 1 });
    await user.click(screen.getByRole('checkbox', { name: 'New rule' }));
    expect(definition().templates.find((t) => t.id === actionCardId)!.ruleSetIds).toEqual([actionRuleId]);

    await goto(router, `/game/${GAME_ID}/cards/${strikeId}`);
    await screen.findByRole('heading', { level: 1 });
    await user.click(screen.getByRole('checkbox', { name: 'New rule 6' }));
    expect(definition().templates.find((t) => t.id === strikeId)!.ruleSetIds).toEqual([strikeRuleId]);

    await goto(router, `/game/${GAME_ID}/cards/${equipmentId}`);
    await screen.findByRole('heading', { level: 1 });
    await user.click(screen.getByRole('checkbox', { name: 'New rule 8' }));
    expect(definition().templates.find((t) => t.id === equipmentId)!.ruleSetIds).toEqual([equipmentRuleId]);

    // ==========================================================================================
    // Export -> import -> play.
    // ==========================================================================================
    const authored = definition();
    const json = exportJson(authored);
    const imported = importJson(json);
    expect(imported.ok).toBe(true);
    if (!imported.ok) return;
    expect(exportJson(imported.definition)).toBe(json);

    const def = imported.definition;

    // (b1) V11-shaped: influence reaches capacity -> the minion moves to Ready, on the round-
    // tripped definition. Same outcome `fixtures.test.ts`'s V11 test proves for real vtesish.
    const state1 = emptyBoard(def, START_STATE_ID);
    const minionInstanceId = place(state1, def, `${uncontrolledId}#0`, minionId, 'm1');
    state1.cards[minionInstanceId].indexValues[capacityId] = 2;
    const lines1: LogLine[] = [];
    let r1 = step(state1, { kind: 'action', action: { kind: 'fireEvent', name: 'onUntap', seat: 0 }, override: false }, lines1, def);
    while (!r1.done) r1 = step(state1, CONTINUE, lines1, def);
    expect(state1.cards[minionInstanceId].indexValues[influenceId]).toBe(1);
    expect(state1.zones[`${readyZoneId}#0`].cardIds).toEqual([]);

    r1 = step(state1, { kind: 'action', action: { kind: 'fireEvent', name: 'onUntap', seat: 0 }, override: false }, lines1, def);
    while (!r1.done) r1 = step(state1, CONTINUE, lines1, def);
    expect(state1.cards[minionInstanceId].indexValues[influenceId]).toBe(2);
    expect(state1.zones[`${readyZoneId}#0`].cardIds).toEqual([minionInstanceId]);

    // (b2) V1-shaped: the PREDATOR of the triggering card's owner is charged, not the active seat.
    // 5 seats, active seat 0; the action card is owned by seat 2, so its predator is seat 1.
    const state2 = emptyBoard(def, START_STATE_ID);
    const cardId = place(state2, def, `${handId}#2`, actionCardId, 'ac1');
    const lines2: LogLine[] = [];
    let result2 = step(
      state2,
      { kind: 'action', action: { kind: 'moveCard', cardId, to: { zoneId: uncontrolledId, seat: { kind: 'seat', index: 2 } }, position: 'top' }, override: false },
      lines2,
      def
    );
    let guard = 0;
    while (true) {
      if (++guard > 10_000) throw new Error('runaway');
      if (state2.interaction?.kind === 'priority') {
        result2 = step(state2, { kind: 'action', action: { kind: 'passPriority' }, override: false }, lines2, def);
      } else if (result2.done) {
        break;
      } else {
        result2 = step(state2, CONTINUE, lines2, def);
      }
    }
    expect(state2.playerPools[poolId]).toEqual([30, 29, 30, 30, 30]);
  }, 30_000);
});
