/**
 * Step 17 — the sprite, the catalog, and the three components that read them.
 *
 * Two halves on purpose: the DOM half (does <use> point at a symbol that exists, does search
 * narrow) and a source/asset half (is the generated pair still in sync, does the attribution still
 * ship). The second half is what silently rots — a regenerated sprite with a stale catalog renders
 * empty boxes and throws no error anywhere.
 */

import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { render, screen, within } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { describe, expect, it, vi } from 'vitest';
import { ICON_CATALOG } from '../../assets/icons/catalog';
import { SPRITE_ICON_COUNT, SPRITE_MARKUP } from '../../assets/icons/sprite';
import { Icon } from './Icon';
import { IconPicker } from './IconPicker';
import { IconSprite } from './IconSprite';

const ASSET_DIR = join(process.cwd(), 'src', 'assets', 'icons');

describe('<Icon>', () => {
  it('points <use> at the sprite symbol for its id', () => {
    const { container } = render(<Icon id="gi-broadsword" />);
    expect(container.querySelector('use')).toHaveAttribute('href', '#gi-broadsword');
  });

  it('is hidden from assistive tech when it carries no label', () => {
    // The common case: a pip whose number, or a button whose text, already says it.
    const { container } = render(<Icon id="gi-broadsword" />);
    const svg = container.querySelector('svg')!;
    expect(svg).toHaveAttribute('aria-hidden', 'true');
    expect(svg).not.toHaveAttribute('role');
  });

  it('becomes a named image when given a label', () => {
    render(<Icon id="gi-broadsword" label="Attack" />);
    const svg = screen.getByRole('img', { name: 'Attack' });
    expect(svg).not.toHaveAttribute('aria-hidden');
  });

  it('keeps .cb-icon when a caller adds its own class', () => {
    // .cb-icon is what makes it 1em and currentColor; losing it on a custom class would silently
    // render a full-size black glyph.
    const { container } = render(<Icon id="gi-shield" className="cb-card__glyph" />);
    expect(container.querySelector('svg')).toHaveClass('cb-icon', 'cb-card__glyph');
  });
});

describe('<IconSprite>', () => {
  it('mounts one symbol per catalog entry', () => {
    const { container } = render(<IconSprite />);
    const ids = [...container.querySelectorAll('symbol')].map((s) => s.id);
    expect(ids).toHaveLength(SPRITE_ICON_COUNT);
    expect(new Set(ids).size).toBe(ids.length); // a duplicate id silently wins/loses at random
  });

  it('resolves every id in the catalog', () => {
    const { container } = render(<IconSprite />);
    const ids = new Set([...container.querySelectorAll('symbol')].map((s) => s.id));
    const dangling = ICON_CATALOG.filter((icon) => !ids.has(icon.id)).map((icon) => icon.id);
    expect(dangling).toEqual([]);
  });

  it('gives every symbol a viewBox', () => {
    // Without it the parent <svg> has no intrinsic geometry and the glyph renders at 0×0.
    const { container } = render(<IconSprite />);
    const missing = [...container.querySelectorAll('symbol')]
      .filter((s) => !s.getAttribute('viewBox'))
      .map((s) => s.id);
    expect(missing).toEqual([]);
  });

  it('is hidden from assistive tech and out of layout', () => {
    const { container } = render(<IconSprite />);
    const svg = container.querySelector('svg')!;
    expect(svg).toHaveAttribute('aria-hidden', 'true');
    expect(svg.getAttribute('style')).toMatch(/width:\s*0/);
  });
});

describe('the generated assets are in sync (AC: L1)', () => {
  it('catalog and sprite agree on the count', () => {
    expect(ICON_CATALOG).toHaveLength(SPRITE_ICON_COUNT);
  });

  it('ships roughly the 300 icons §8 asked for', () => {
    expect(SPRITE_ICON_COUNT).toBeGreaterThanOrEqual(280);
    expect(SPRITE_ICON_COUNT).toBeLessThanOrEqual(340);
  });

  it('namespaces every id under gi- and never repeats one', () => {
    const ids = ICON_CATALOG.map((i) => i.id);
    expect(ids.filter((id) => !id.startsWith('gi-'))).toEqual([]);
    expect(new Set(ids).size).toBe(ids.length);
  });

  it('gives every icon a name and searchable tags', () => {
    const bare = ICON_CATALOG.filter((i) => i.name.trim() === '' || i.tags.length === 0);
    expect(bare).toEqual([]);
  });

  it('references nothing over the network', () => {
    // An <image href="https://…"> or an external-url filter inside a path would be a live request
    // on every render — exactly what L1 forbids.
    expect(SPRITE_MARKUP).not.toMatch(/https?:\/\//i);
  });

  it('keeps the do-not-edit header, so a hand edit is obvious in review', () => {
    for (const file of ['sprite.tsx', 'catalog.ts']) {
      expect(readFileSync(join(ASSET_DIR, file), 'utf8')).toContain('GENERATED by scripts/gen-icons.mjs');
    }
  });

  it('ships the CC BY 3.0 attribution file', () => {
    const attribution = readFileSync(join(ASSET_DIR, 'ATTRIBUTION.md'), 'utf8');
    expect(attribution).toContain('CC BY 3.0');
    expect(attribution).toContain('game-icons');
  });
});

describe('<IconPicker>', () => {
  it('shows the whole catalog before anything is typed', () => {
    render(<IconPicker onSelect={vi.fn()} />);
    expect(screen.getAllByRole('button')).toHaveLength(ICON_CATALOG.length);
  });

  it('narrows by name', async () => {
    const user = userEvent.setup();
    render(<IconPicker onSelect={vi.fn()} />);
    await user.type(screen.getByRole('searchbox', { name: /search icons/i }), 'broadsword');

    const cells = screen.getAllByRole('button');
    expect(cells.length).toBeLessThan(ICON_CATALOG.length);
    expect(cells.every((c) => /sword/i.test(c.textContent ?? ''))).toBe(true);
  });

  it('narrows by tag, not just by the visible name', async () => {
    // Category is a tag: "weapons" matches icons whose displayed name never says weapon.
    const user = userEvent.setup();
    render(<IconPicker onSelect={vi.fn()} />);
    await user.type(screen.getByRole('searchbox'), 'weapons');

    const shown = screen.getAllByRole('button').length;
    const expected = ICON_CATALOG.filter((i) => i.tags.includes('weapons')).length;
    expect(shown).toBe(expected);
    expect(shown).toBeGreaterThan(0);
  });

  it('treats a second word as a further narrowing, not an alternative', async () => {
    const user = userEvent.setup();
    render(<IconPicker onSelect={vi.fn()} />);
    await user.type(screen.getByRole('searchbox'), 'weapons');
    const broad = screen.getAllByRole('button').length;

    await user.type(screen.getByRole('searchbox'), ' axe');
    expect(screen.getAllByRole('button').length).toBeLessThan(broad);
  });

  it('says so when nothing matches, instead of rendering an empty grid', async () => {
    const user = userEvent.setup();
    render(<IconPicker onSelect={vi.fn()} />);
    await user.type(screen.getByRole('searchbox'), 'zzzznotanicon');

    expect(screen.getByText(/no icon matches/i)).toBeInTheDocument();
    expect(screen.queryByRole('button')).not.toBeInTheDocument();
  });

  it('reports the chosen id to its caller', async () => {
    const onSelect = vi.fn();
    const user = userEvent.setup();
    render(<IconPicker onSelect={onSelect} />);
    await user.type(screen.getByRole('searchbox'), 'broadsword');
    await user.click(screen.getAllByRole('button')[0]);

    expect(onSelect).toHaveBeenCalledTimes(1);
    expect(onSelect.mock.calls[0][0]).toMatch(/^gi-/);
  });

  it('announces the current value as pressed', () => {
    render(<IconPicker value="gi-broadsword" onSelect={vi.fn()} />);
    const pressed = screen.getAllByRole('button', { pressed: true });
    expect(pressed).toHaveLength(1);
    expect(within(pressed[0]).getByText(/broadsword/i)).toBeInTheDocument();
  });

  it('carries the CC BY credit the licence requires', () => {
    // Shipping ATTRIBUTION.md in the repo does not satisfy CC BY for the running app; this line does.
    render(<IconPicker onSelect={vi.fn()} />);
    expect(screen.getByText(/CC BY 3\.0/)).toBeInTheDocument();
    expect(screen.getByRole('link', { name: /game-icons\.net/i })).toHaveAttribute(
      'href',
      'https://game-icons.net'
    );
  });
});
